import { Tool, CategoryInfo, FaqItem } from './types.ts';

export const CATEGORIES: CategoryInfo[] = [
  {
    id: 'analyzer',
    name: 'Text Analyzers',
    description: 'Analyze word density, counts, and reading statistics with pixel perfection.',
    colorClass: 'emerald',
  },
  {
    id: 'cleaner',
    name: 'Formatting Cleaners',
    description: 'Purge noisy characters, duplicate white spaces, and broken layout wraps instantly.',
    colorClass: 'indigo',
  },
  {
    id: 'converter',
    name: 'Casing Converters',
    description: 'Shift text between standard casing guidelines, camelCase, snake_case, and more.',
    colorClass: 'amber',
  },
];

export const TOOLS: Tool[] = [
  {
    id: 'tools/word-counter',
    title: 'Word Counter',
    description: 'Count words, sentences, paragraphs, and estimate read time.',
    longDescription: 'Our advanced word counter delivers immediate analysis of your writing. Ideal for blog articles, SEO copywriters, or essay submissions, it measures reading time, word metrics, and paragraph density instantly.',
    iconName: 'FileText',
    category: 'analyzer',
    seoTitle: 'Free Online Word Counter - Live Character & Reading Time Metrics',
    seoDescription: 'Count words, sentences, and paragraphs in real-time. Calculate estimated reading time, keyword density, and overall text statistics with our fully client-side analyzer.',
    keywords: ['word counter', 'counting words', 'reading time', 'text density', 'sentence count', 'seo toolkit'],
  },
  {
    id: 'tools/character-counter',
    title: 'Character Counter',
    description: 'Count characters with/without spaces, tabs, lines, and bytes.',
    longDescription: 'Keep track of strict social media limits (like X/Twitter, LinkedIn, meta descriptions) by counting characters precisely, with granular breakdowns of spacing and byte weights.',
    iconName: 'Hash',
    category: 'analyzer',
    seoTitle: 'Character Counter Tool - Limit Checker for Social Media & SEO Meta',
    seoDescription: 'Count characters with and without spacing in real-time. Find byte size, tab characters, and lines helper counters for social posts, SMS, and SEO metadata.',
    keywords: ['character count', 'no spaces', 'byte counter', 'line counter', 'text limit checker', 'social media length'],
  },
  {
    id: 'tools/remove-line-breaks',
    title: 'Remove Line Breaks',
    description: 'Instantly strip standard line wraps, return characters, or double breaks.',
    longDescription: 'Tired of copy-pasting text from PDFs or e-mails containing awkward line breaks? Automatically bridge paragraphs together or flatten entire texts into a clean single line with custom separators.',
    iconName: 'Unwrap', // We will map this code icon to Lucide (e.g., AlignLeft or WrapText)
    category: 'cleaner',
    seoTitle: 'Remove Line Breaks Online - Format PDF Text & Email Wraps',
    seoDescription: 'Purge unwanted line wraps, carriage returns, and breaks. Re-format awkward PDF copy, align words, or flatten messages into single-line layouts.',
    keywords: ['strip line breaks', 'remove enter keys', 'format pdf copy', 'flatten paragraph', 'line wrapper remover'],
  },
  {
    id: 'tools/remove-extra-spaces',
    title: 'Remove Extra Spaces',
    description: 'Strip double spacings, extra tabulators, leading/trailing whitespace.',
    longDescription: 'Sanitize messy code, draft posts, or imported tables. This quick-formatting clean-up strips leading margins, trailing spacing, converts multiple blocks of spaces into standard white spacing, and cleans tabs.',
    iconName: 'Eraser',
    category: 'cleaner',
    seoTitle: 'Remove Extra Spaces & Tabs - Online Whitespace Sanitizer',
    seoDescription: 'Strip duplicate white spaces, remove trailing and leading tabs, and convert block spaces. Get clean text formatting for clean web layout drafts and coding scripts.',
    keywords: ['whitespace remover', 'strip duplicate spaces', 'trim whitespace', 'clean space spacing', 'tab remover'],
  },
  {
    id: 'tools/case-converter',
    title: 'Case Converter',
    description: 'Convert text casing (UPPER, lower, Title, Sentence, camel, snake, kebab).',
    longDescription: 'Seamlessly shift your paragraphs between visual capitalization presets. Fast format code constants (UPPER_CASE), titles (Title Case), URL slugs (kebab-case), or standard email grammar layouts.',
    iconName: 'Type',
    category: 'converter',
    seoTitle: 'Online Case Converter - Toggle UPPERCASE, lowercase, Title Case',
    seoDescription: 'Convert casing formats instantly. Choose between sentence case, Title Case, camelCase, snake_case, kebab-case, or inverse casings with a single click.',
    keywords: ['case converter', 'capitalization tool', 'to lowercase', 'to uppercase', 'title case format', 'slug generator'],
  },
  {
    id: 'tools/text-compare',
    title: 'Text Compare',
    description: 'Compare two texts side-by-side or inline to find exact line alignments, modified sentences, and code adjustments.',
    longDescription: 'Compare your revision drafts or source code parameters instantly. Our browser-based diff engine isolates additions, deletion offsets, and character variations beautifully.',
    iconName: 'GitCompare',
    category: 'analyzer',
    seoTitle: 'Text Compare Tool – Compare Text Online Free',
    seoDescription: 'Compare two texts online and instantly find differences, changed words, added text, removed text, and character variations.',
    keywords: ['text compare', 'diff checker', 'compare texts online', 'find differences', 'text comparator', 'code difference'],
  },
  {
    id: 'tools/slug-generator',
    title: 'Slug Generator',
    description: 'Convert post titles, headers or custom strings into clean SEO-friendly URL slugs instantly.',
    longDescription: 'Convert any raw headline or blog title into a human-friendly web address token. Prune helper stopwords, clear punctuation, replace spacing with dashes, or convert character cases.',
    iconName: 'Link2',
    category: 'converter',
    seoTitle: 'SEO Slug Generator Online',
    seoDescription: 'Generate SEO-friendly URL slugs instantly. Convert titles into clean search-engine-friendly URLs.',
    keywords: ['slug generator', 'url slug', 'seo friendly url', 'convert title to slug', 'clean url generator', 'create slug format'],
  },
  {
    id: 'tools/url-encoder',
    title: 'URL Encoder / Decoder',
    description: 'Encode or decode URL characters, safe-formatting parameters for internet transmission instantly.',
    longDescription: 'Our advanced browser URI translation tool encodes unreserved characters or decodes percent notations in real-time. Choose custom formats for spaces or custom parameters securely.',
    iconName: 'Globe',
    category: 'converter',
    seoTitle: 'URL Encoder Online Free',
    seoDescription: 'Encode URLs instantly for safe transmission on the web.',
    keywords: ['url encoder', 'url encode online', 'percent encoding', 'decoder url', 'decode url percent', 'safe uri string'],
  },
  {
    id: 'tools/url-decoder',
    title: 'URL Decoder',
    description: 'Decode percent-encoded strings or dynamic web parameters back to clean readable text instantly.',
    longDescription: 'Extract plain legible parameters from escaped text. Configurable plus variables (+) translations and path-query cleaner options are fully supported client-side.',
    iconName: 'Unlock',
    category: 'converter',
    seoTitle: 'URL Decoder Online Free – Decode Percent-Encoded URLs',
    seoDescription: 'Decode percent-encoded URLs and escaped web parameters instantly online. Revert %20 to spaces, %3A to colons, and safely extract plain readable text.',
    keywords: ['url decoder', 'url decode online', 'percent decoding', 'unencode string', 'decode percent text', 'readable uri parameter'],
  },
  {
    id: 'tools/fancy-text-generator',
    title: 'Fancy Text Generator',
    description: 'Generate stylish fancy text fonts for Instagram, Facebook, WhatsApp, Threads, X, and social media.',
    longDescription: 'Generate stylish font variations in standard cursive scripts, bold serifs, Fraktur Gothic structures, bubble circles, and other unique unicode blocks in one click.',
    iconName: 'Sparkles',
    category: 'converter',
    seoTitle: 'Fancy Text Generator Online',
    seoDescription: 'Generate stylish fancy text fonts for Instagram, Facebook, WhatsApp, Threads, X, and social media.',
    keywords: ['fancy text generator', 'stylish text', 'unicode fonts', 'instagram bio fonts', 'facebook text generator', 'cool text decorations'],
  },
  {
    id: 'tools/html-encoder',
    title: 'HTML Encoder',
    description: 'Convert HTML code or strings into encoded HTML entities to display nested tags safely.',
    longDescription: 'Protect your web layouts and prevent cross-site scripting vulnerabilities by translating sensitive syntax markers—such as tags, quotes, and ampersands—into fully encoded HTML entity notations.',
    iconName: 'FileText',
    category: 'converter',
    seoTitle: 'HTML Encoder Tool Online Free',
    seoDescription: 'Convert HTML code into encoded HTML entities instantly. Free online HTML Encoder.',
    keywords: ['html encoder', 'encode html entities', 'html hex encoder', 'escape html tag', 'prevent xss string', 'special character encoder'],
  },
  {
    id: 'tools/html-decoder',
    title: 'HTML Decoder',
    description: 'Decode HTML entities back into readable HTML code instantly.',
    longDescription: 'Convert escaped character designations or numeric representations—like &amp;lt;, &amp;gt;, and &amp;quot;—into their literal character equivalents instantly, restoring clean text or original markup source code.',
    iconName: 'Unlock',
    category: 'converter',
    seoTitle: 'HTML Decoder Tool Online',
    seoDescription: 'Decode HTML entities back into readable HTML code instantly. Free privacy-first online HTML entity decoder tool.',
    keywords: ['html decoder', 'decode html entities', 'unescape html tags', 'convert html entity', 'html code unescaper', 'entity decoder online'],
  },
  {
    id: 'tools/base64-encoder',
    title: 'Base64 Encoder',
    description: 'Encode text into Base64 format instantly using our free online Base64 Encoder.',
    longDescription: 'Secure your binary-to-text data configurations or standardize string characters cleanly into standard RFC-compliant Base64 formats. Fully client-side, offline-aware, and metadata-secure.',
    iconName: 'Link2',
    category: 'converter',
    seoTitle: 'Base64 Encoder Online - Convert Text to Base64 Free',
    seoDescription: 'Encode text into Base64 format instantly using our free online Base64 Encoder. Compliant, safe, and operates locally.',
    keywords: ['base64 encoder', 'base64 encode', 'text to base64', 'base64 converter', 'binary to text', 'encode string to base64'],
  },
  {
    id: 'tools/base64-decoder',
    title: 'Base64 Decoder',
    description: 'Decode Base64 strings instantly and convert them back into readable text.',
    longDescription: 'Reverse Base64 encoded streams back to readable UTF-8 string outputs. Includes client-side safety verification, live error checking, and text download capabilities.',
    iconName: 'Unlock',
    category: 'converter',
    seoTitle: 'Base64 Decoder Online Free - Convert Base64 back to Text',
    seoDescription: 'Decode Base65 strings back to clean readable text instantly using our secure, fully local client-side Base64 decoder tool.',
    keywords: ['base64 decoder', 'decode base64', 'base64 to text', 'base64 unescape', 'base64 parser', 'decrypt base64 online'],
  },
  {
    id: 'tools/text-sorter',
    title: 'Text Sorter',
    description: 'Sort text lines alphabetically, reverse order, randomize lists, and remove duplicates instantly.',
    longDescription: 'Organize list structures, files, code lines, or items alphabetically in A-Z or Z-A order. Reorder lines in reverse, shuffle randomly, and remove redundant duplicate lines instantly.',
    iconName: 'ArrowUpDown',
    category: 'cleaner',
    seoTitle: 'Text Sorter Tool Online - Sort Lines Alphabetically Free',
    seoDescription: 'Sort text lines alphabetically (A-Z, Z-A), reverse order, randomize lists, and eliminate duplicates instantly with our free online Text Sorter Tool.',
    keywords: ['text sorter', 'alphabetical sorter', 'sort lines online', 'remove duplicate lines', 'shuffle lines', 'sort text a-z'],
  },
  {
    id: 'tools/text-reverser',
    title: 'Text Reverser',
    description: 'Reverse text, words, lines, and characters instantly with our free online Text Reverser Tool.',
    longDescription: 'Flip your essays, lines, code, lists, or letters backwards with our extensive suite of text reversing filters. Support for reversing characters, reverse by line structures, preserving or reversing words, and real-time live preview.',
    iconName: 'ArrowLeftRight',
    category: 'converter',
    seoTitle: 'Text Reverser Tool Online Free - Reverse Characters & Words',
    seoDescription: 'Reverse text characters, whole word orders, lines, or paragraphs instantly with our modern, fully client-side online Text Reverser Tool.',
    keywords: ['text reverser', 'reverse characters', 'reverse words', 'reverse text online', 'backwards text generator', 'flip text generator'],
  },
];

export const FAQS: FaqItem[] = [
  {
    id: 1,
    question: 'How secure is my text on TextToolkitHub?',
    answer: 'Extremely secure! All text manipulation, analysis, and cleaning happen 100% locally inside your web browser. Absolutely no data is uploaded, processed, or saved on external servers, making it completely private and confidential.',
  },
  {
    id: 2,
    question: 'Can I use this portal on my smartphone?',
    answer: 'Yes! TextToolkitHub is designed from the ground up to be fully mobile-responsive. Layout arrays, text areas, action shortcuts, and result counts scale perfectly to fit your smartphone, tablet, or desktop screen.',
  },
  {
    id: 3,
    question: 'Does TextToolkitHub support dark mode?',
    answer: 'Absolutely. We offer a high-performance dark mode that helps protect your eyes from blue light fatigue, especially during late-night writing or editing sessions. Use the theme toggle on the upper-right corner of the navigation bar to shift layouts.',
  },
  {
    id: 4,
    question: 'Are there any character or file limits?',
    answer: 'The tools process text instantly in real-time. While we do not impose artificial limits, very large documents (e.g., millions of characters) will be constrained only by your device memory and browser capability.',
  },
];
